# Generated by Django 6.0 on 2026-01-11 02:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='level2_credentialas',
            new_name='level2_credentials',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='transaction_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('250000.00'), max_digits=12),
        ),
    ]
