# Generated by Django 6.0 on 2026-01-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_level2_credentialas_userprofile_level2_credentials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_pin',
            field=models.BooleanField(default=False),
        ),
    ]
