# Generated by Django 6.0 on 2026-02-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userprofile_pending_balance_withdrawable_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
