# Generated by Django 6.0 on 2026-02-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_userprofile_transaction_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='level2credentials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='level3credentials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
