# Generated by Django 6.0 on 2026-02-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_level2credentials_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level2credentials',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='level3credentials',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=12),
        ),
    ]
