# Generated by Django 6.0 on 2026-02-23 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_bankaccountdetails_userprofile_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bank_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_bank_details', to='account.bankaccountdetails'),
        ),
    ]
