# Generated by Django 6.0 on 2026-04-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_phoneverificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverificationrequest',
            name='message_id',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='phoneverificationrequest',
            name='pin_id',
            field=models.CharField(max_length=7),
        ),
    ]
