# Generated by Django 6.0 on 2026-05-09 01:19

import django.db.models.deletion
import secrets
import string
from django.conf import settings
from django.db import migrations, models


def backfill_referral_codes(apps, schema_editor):
    UserProfile = apps.get_model('account', 'UserProfile')
    alphabet = string.ascii_uppercase + string.digits
    used_codes = set(
        UserProfile.objects.exclude(referral_code__isnull=True)
        .exclude(referral_code='')
        .values_list('referral_code', flat=True)
    )

    for user in UserProfile.objects.filter(models.Q(referral_code__isnull=True) | models.Q(referral_code='')):
        while True:
            code = ''.join(secrets.choice(alphabet) for _ in range(10))
            if code not in used_codes:
                used_codes.add(code)
                user.referral_code = code
                user.save(update_fields=['referral_code'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_phoneverificationrequest_message_id_and_more'),
        ('order', '0006_alter_giftcardorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_referral_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, unique=True),
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Paid', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qualifying_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_commissions', to='order.giftcardorder')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_referral_commissions', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referrer', 'status'], name='ref_comm_referrer_status_idx'), models.Index(fields=['referred_user'], name='ref_comm_referred_idx')],
                'constraints': [models.UniqueConstraint(fields=('referrer', 'referred_user'), name='unique_referral_commission_per_referred_user')],
            },
        ),
    ]
