services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-change-this-in-production
      - TERMII_API_KEY=TLPlVvPYstukdbJXHylgeDADwRVkYOQmptbCdZWzYQbmiqJMszigizEjzgFcoC
      - TERMII_BASE_URL=https://v3.api.termii.com
      - TERMII_PHONE_OTP_SENDER_ID=Greatxchnge
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    restart: unless-stopped
