services:
  web:
    build: .
    container_name: grx-backend
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=iuytiu897thkm,nui987tyhkjkoiuyhjkliouyuYTUIOKLJHGFYTUIiuytghj
      - TERMII_API_KEY=TLPlVvPYstukdbJXHylgeDADwRVkYOQmptbCdZWzYQbmiqJMszigizEjzgFcoC
      - TERMII_BASE_URL=https://v3.api.termii.com
      - TERMII_PHONE_OTP_SENDER_ID=Greatxchnge
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    restart: unless-stopped
  
  redis:
    image: redis:8.0-alpine
    container_name: grx-redis
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
    restart: unless-stopped

  celery:
    container_name: grx-celery
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A gtx worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis
  
  celery-beat:
    container_name: grx-celery-beat
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A gtx beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - redis
  
  flower:
    container_name: grx-flower
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A gtx flower --address=0.0.0.0 --port=5555
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    depends_on:
      - redis
