# Generated by Django 6.0 on 2025-12-31 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardnames',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_card_name_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='giftcardstore',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_card_store_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
