# Generated by Django 6.0 on 2026-01-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_giftcardnames_user_alter_giftcardstore_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardstore',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Popular', 'Popular'), ('Shopping', 'Shopping')], default='All', max_length=50),
        ),
    ]
