# Generated by Django 6.0 on 2026-01-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_giftcardstore_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcardstore',
            name='image',
        ),
        migrations.AddField(
            model_name='giftcardstore',
            name='type',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Encode', 'Encode')], default='Physical', max_length=50),
        ),
    ]
