# Generated by Django 6.0 on 2026-01-08 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_giftcardstore_image_giftcardstore_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcardstore',
            name='type',
        ),
    ]
