# Generated by Django 6.0 on 2026-01-08 01:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_giftcardstore_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcardstore',
            name='rate',
        ),
        migrations.AddField(
            model_name='giftcardnames',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
