# Generated by Django 6.0 on 2026-01-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_remove_giftcardstore_rate_giftcardnames_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardnames',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
