# Generated by Django 6.0 on 2026-01-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_giftcardnames_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardnames',
            name='type',
            field=models.CharField(choices=[('Both', 'Both'), ('Physical', 'Physical'), ('E-ncode', 'E-ncode')], default='Both', max_length=50),
        ),
    ]
