# Generated by Django 6.0 on 2026-01-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_giftcardnames_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardstore',
            name='image',
            field=models.ImageField(null=True, upload_to='gift stores'),
        ),
    ]
