# Generated by Django 6.0 on 2026-01-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_giftcardstore_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardnames',
            name='type',
            field=models.CharField(choices=[('Both', 'Both'), ('Physical', 'Physical'), ('E-code', 'E-code')], default='Both', max_length=50),
        ),
    ]
