# Generated by Django 6.0 on 2026-01-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_alter_giftcardnames_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardstore',
            name='category',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Shopping', 'Shopping')], default='All', max_length=50),
        ),
    ]
