# Generated by Django 6.0 on 2026-02-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_giftcardstore_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardnames',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='giftcardstore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
