# Generated by Django 6.0 on 2026-05-09 06:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_giftcardnames_created_at_giftcardstore_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardnames',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
