# Generated by Django 6.0 on 2026-01-14 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0011_alter_giftcardstore_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Physical', 'Physical'), ('E-Code', 'E-Code')], max_length=50)),
                ('image', models.ImageField(upload_to='orders/')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Processing', max_length=50)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.giftcardnames')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
