# Generated by Django 6.0 on 2026-01-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcardorder',
            old_name='name',
            new_name='card',
        ),
        migrations.AddField(
            model_name='giftcardorder',
            name='e_code_pin',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='giftcardorder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/'),
        ),
    ]
