# Generated by Django 6.0 on 2026-02-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_name_giftcardorder_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
