# Generated by Django 6.0 on 2026-02-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_giftcardorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
