# Generated by Django 6.0 on 2026-05-09 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0002_alter_withdrawal_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalLimitUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_limit_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'user_id'],
                'indexes': [models.Index(fields=['date'], name='withdrawal_usage_date_idx'), models.Index(fields=['user', 'date'], name='withdrawal_usage_user_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_withdrawal_usage_per_user_date')],
            },
        ),
    ]
