"""
Django settings for gtx project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decimal import Decimal

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path: Path) -> None:
    """Load simple KEY=VALUE pairs from a local .env file into os.environ."""
    if not path.exists():
        return

    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


load_env_file(BASE_DIR / '.env')


def env_first(*names: str, default: str = '') -> str:
    """Return the first configured environment value from a list of aliases."""
    for name in names:
        value = os.environ.get(name)
        if value:
            return value
    return default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-owfkfy9phx8k_59h*$su@!u62o5*ol3jckk19-y7rw6eqsf3^i')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = ["*"]
# ALLOWED_HOSTS = ['127.0.0.1', '.vercel.app']

# Allow ngrok domains for CSRF
# CSRF_TRUSTED_ORIGINS = [
#     "https://*.ngrok-free.app",
#     "https://*.ngrok.io",
# ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # installed apps
    'rest_framework',
    'rest_framework_simplejwt',
    'phonenumber_field',
    'corsheaders',
    'drf_spectacular',
    'django_celery_beat',

    # project apps
    'account',
    'cards',
    'control',
    'order',
    'withdrawal',
    'notification',
    'logs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Logging middleware (must be after CommonMiddleware)
    'logs.middleware.RequestLoggingMiddleware',
    'logs.middleware.ExceptionLoggingMiddleware',
]

ROOT_URLCONF = 'gtx.urls'
AUTH_USER_MODEL = "account.UserProfile"
WSGI_APPLICATION = 'gtx.wsgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "KEY_PREFIX": "backend",
        "TIMEOUT": 300,
    }
}

STORAGES = {
  "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

WSGI_APPLICATION = 'gtx.wsgi.application'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'GTX Crypto App',
    'DESCRIPTION': 'This is a platform where you sell giftcards',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'ENUM_NAME_OVERRIDES': {
        'CredentialStatusEnum': [
            ('Pending', 'Pending'),
            ('Approved', 'Approved'),
            ('Rejected', 'Rejected'),
        ],
        'UserStatusEnum': [
            ('Active', 'Active'),
            ('Warning', 'Warning'),
            ('Disabled', 'Disabled'),
            ('Under Review', 'Under Review'),
        ],
        'ReferralCommissionStatusEnum': [
            ('Pending', 'Pending'),
            ('Paid', 'Paid'),
            ('Cancelled', 'Cancelled'),
        ],
        'NotificationEventStatusEnum': [
            ('pending', 'Pending'),
            ('sent', 'Sent'),
            ('failed', 'Failed'),
        ],
        'GiftCardNameTypeEnum': [
            ('Both', 'Both'),
            ('Physical', 'Physical'),
            ('E-code', 'E-code'),
        ],
        'GiftCardOrderTypeEnum': [
            ('Physical', 'Physical'),
            ('E-Code', 'E-Code'),
        ],
        'WithdrawalStatusEnum': [
            ('Pending', 'Pending'),
            ('Approved', 'Approved'),
            ('Rejected', 'Rejected'),
            ('Cancelled', 'Cancelled'),
            ('Processing', 'Processing'),
            ('Completed', 'Completed'),
            ('Failed', 'Failed'),
        ],
    },
    # OTHER SETTINGS
}


from datetime import timedelta
from celery.schedules import crontab

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.environ.get('DATABASE_URL', "postgresql://postgres:NgbrBsrhtnqPuRblRHfcKKXDmWnGVTlm@tramway.proxy.rlwy.net:49619/railway"),
#         conn_max_age=600,
#         conn_health_checks=True,
#     ),
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR/"staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / 'static'
    ]

MEDIA_ROOT = BASE_DIR / "media" 
MEDIA_URL = '/media/'

EMAIL_FROM = os.environ.get('AUTHEMAIL_DEFAULT_EMAIL_FROM') or 'gusanujoshua39@gmail.com'
EMAIL_BCC = os.environ.get('AUTHEMAIL_DEFAULT_EMAIL_BCC') or 'gusanujoshua39@gmail.com'

EMAIL_HOST = os.environ.get('AUTHEMAIL_EMAIL_HOST') or 'smtp.gmail.com'
EMAIL_PORT = os.environ.get('AUTHEMAIL_EMAIL_PORT') or 587
EMAIL_HOST_USER = os.environ.get('AUTHEMAIL_EMAIL_HOST_USER') or 'gusanujoshua39@gmail.com'
EMAIL_HOST_PASSWORD = os.environ.get('AUTHEMAIL_EMAIL_HOST_PASSWORD') or 'gelm uqlv fqoh kgjn'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT') or 10)

TWILIO_ACCOUNT_SID = env_first('TWILIO_ACCOUNT_SID', 'TWILIO_SID').strip()
TWILIO_AUTH_TOKEN = env_first('TWILIO_AUTH_TOKEN', 'TWILIO_AUTH_TOKEN_SECRET', 'TWILIO_SECRET', 'TWILIO_SECRETE').strip()
_twilio_app_name = os.environ.get('TWILIO_APP_NAME', '').strip()
TWILIO_VERIFY_SERVICE_SID = env_first('TWILIO_VERIFY_SERVICE_SID', 'TWILIO_APP_SID').strip()
if not TWILIO_VERIFY_SERVICE_SID and _twilio_app_name.upper().startswith('VA'):
    TWILIO_VERIFY_SERVICE_SID = _twilio_app_name
TWILIO_VERIFY_SERVICE_NAME = env_first('TWILIO_VERIFY_SERVICE_NAME', 'TWILIO_APP_NAME').strip()
TWILIO_VERIFY_BASE_URL = os.environ.get(
    'TWILIO_VERIFY_BASE_URL',
    'https://verify.twilio.com/v2',
).strip().rstrip('/')
TWILIO_VERIFY_CHANNEL = os.environ.get('TWILIO_VERIFY_CHANNEL', 'sms').strip()
TWILIO_REQUEST_TIMEOUT_SECONDS = int(os.environ.get('TWILIO_REQUEST_TIMEOUT_SECONDS', '15'))



# Expo push notifications
# EXPO_ACCESS_TOKEN is only required if "Enhanced Security for Push
# Notifications" is enabled on the Expo project; otherwise leave it blank.
EXPO_ACCESS_TOKEN = os.environ.get('EXPO_ACCESS_TOKEN', '').strip()
EXPO_PUSH_TIMEOUT_SECONDS = int(os.environ.get('EXPO_PUSH_TIMEOUT_SECONDS', '10'))
# Force Android delivery via FCM v1. Leave unset (None) to let Expo decide;
# set to 'true'/'false' only if you know your FCM credential setup.
_expo_force_fcm_v1 = os.environ.get('EXPO_FORCE_FCM_V1')
EXPO_FORCE_FCM_V1 = (
    None if _expo_force_fcm_v1 is None
    else _expo_force_fcm_v1.lower() in ('true', '1', 'yes')
)


CELERY_BROKER_URL = os.environ.get("CELERY_BROKER", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_BACKEND", "redis://redis:6379/0")
CELERY_BEAT_SCHEDULE = {
    "refresh-daily-withdrawal-limits": {
        "task": "withdrawal.tasks.refresh_daily_withdrawal_limits",
        "schedule": crontab(hour=0, minute=5),
    },
}

REFERRAL_QUALIFYING_AMOUNT = Decimal(os.environ.get("REFERRAL_QUALIFYING_AMOUNT", "100.00"))
REFERRAL_COMMISSION_PERCENT = Decimal(os.environ.get("REFERRAL_COMMISSION_PERCENT", "10.00"))


# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # For development only
# Logging Configuration
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# Create log files if they don't exist
for log_file in ['user_activity.log', 'requests.log', 'errors.log', 'all.log']:
    log_path = LOGS_DIR / log_file
    log_path.touch(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{asctime}] {levelname} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'request_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOGS_DIR / 'requests.log',
            'when': 'D',  # Rotate daily
            'interval': 1,
            'backupCount': 90,  # Keep 90 days (3 months)
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'error_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'when': 'D',  # Rotate daily
            'interval': 1,
            'backupCount': 90,  # Keep 90 days (3 months)
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'all_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOGS_DIR / 'all.log',
            'when': 'D',  # Rotate daily
            'interval': 1,
            'backupCount': 90,  # Keep 90 days (3 months)
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console', 'all_file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'all_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'error_file', 'all_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'request_logger': {
            'handlers': ['console', 'request_file', 'all_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'print': {
            'handlers': ['all_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
